### ISSUE TITLE
Restriced by CORS

### ISSUE THREAD

**Issue by MehranDHN** [nat236919/Covid2019API#17]
Does it restricted by CORS?

**Comment by DamienDeloubes** [comment]
Would like to know aswel

**Comment by nat236919** [comment]
Hello, I'm not familiar with this term yet. Could you elaborate?

**Comment by impactotecnologico** [comment]
Hi,

We want to build a webapp informing about the global covid cases.

Our idea is to use two of your apis:

https://covid2019-api.herokuapp.com/v2/country/spain and
https://covid2019-api.herokuapp.com/timeseries/confirmed

But when we try to fetch, we receive an error in our frontend:

Access to XMLHttpRequest at 'http://covid2019-api.herokuapp.com/v2/country/spain' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

To solve that, you need to enable the access from other domains using CORS configuration:

https://fastapi.tiangolo.com/tutorial/cors/ something like:

```
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
```

after of `app = FastAPI()`

**Comment by nat236919** [comment]
Hi, I've commited https://github.com/nat236919/Covid2019API/commit/c38b1ad6fde08e2618d89520ab431fb5407f42d0

Hope this will solve the problem.
