### ISSUE TITLE
Ist it possible to add an array for the timeseries dates?

### ISSUE THREAD

**Issue by brim-borium** [nat236919/Covid2019API#18]
Hi, is it possible that the timeseries api gives back an array of dates instead of each date indivudally? 

https://covid2019-api.herokuapp.com/timeseries/confirmed
https://covid2019-api.herokuapp.com/timeseries/deaths
https://covid2019-api.herokuapp.com/timeseries/recovered

**Comment by nat236919** [comment]
https://github.com/nat236919/Covid2019API/commit/6344eb3346abc9b4ee5ea9497cbb211b223e014d I hope this will do

**Comment by brim-borium** [comment]
Looks good to me :)
