### ISSUE TITLE
API returning wrong values

### ISSUE THREAD

**Issue by RamanujamVaradhan** [nat236919/Covid2019API#25]
API returning wrong values at 6:22 PM pacific on 14-Mar-2020

![image](https://user-images.githubusercontent.com/57071016/76693370-e24e7280-6620-11ea-96f6-a6666d3e544c.png)

**Comment by nat236919** [comment]
According to https://github.com/CSSEGISandData/COVID-19/issues/746, the source data is empty due to unexpected reasons.

This issue is normally fixed in a matter of hours.

**Comment by la-colinares** [comment]
Your v2/total endpoint returns the data from 3/13/2020 but today is 3/15/2020, can you make it more updated? Like the /total from v1, the date is 3/14/2020 (but there's a problem with results). 

Thank you!

**Comment by la-colinares** [comment]
Hello, I checked again the endpoints, your v2/current return the data from 3/14/2020 but your v2/total return the data from 3/13/2020. Why not the same?

Thank you!

**Comment by nat236919** [comment]
Thank you for bringing this to my attention. It's been debugged.
https://github.com/nat236919/Covid2019API/commit/a44c57ad0cfb76cfcee1c4b50b124233a34f5675
