### ISSUE TITLE
v1 API Endpoints is more updated than v2 Endpoints.

### ISSUE THREAD

**Issue by la-colinares** [nat236919/Covid2019API#27]
This v1 is more updated compare to v2: 
https://covid2019-api.herokuapp.com/current_list
- current date: 3/14/2020

v2:
https://covid2019-api.herokuapp.com/v2/current
- current date: 3/13/2020

Can you fix that? Thank you so much.

**Comment by nat236919** [comment]
https://github.com/nat236919/Covid2019API/commit/a44c57ad0cfb76cfcee1c4b50b124233a34f5675
