### ISSUE TITLE
Key Error: when a country has a space or uses an abbreviation

### ISSUE THREAD

**Issue by nat236919** [nat236919/Covid2019API#3]
Ex.) South Korea

This will show an error when using 

`https://corona-api.herokuapp.com/country/south korea`

**Comment by nat236919** [comment]
South Korea, United Arab Emirates

**Comment by nat236919** [comment]
UK, US

**Comment by dawenx** [comment]
i noticed you changed "Mainland China" to "China", you might wanted to think about this a little bit more as Taiwan, Hong Kong, Macau has its own country/region name. i think that's why JHU chooses to use "Mainland China". just my 2 cents.

**Comment by cbunicef** [comment]
It would be very useful for my application if you included ISO two and three-letter country codes. That might also address some of these non-standard naming questions.

**Comment by nat236919** [comment]
@dawenx  @cbunicef 
Thank you for your comments. Sure, I'm planning to add keep countries' original names as well as ISO two.

Please feel free to suggest more since I'm still fairly new.

**Comment by nat236919** [comment]
https://github.com/nat236919/Covid2019API/commit/1fa2fc7061180acfaf6631689ed2e0042f5fd148
The draft of #3 search by a country key or ISO (alpha2)

**Comment by array05** [comment]
Надеюсь json данные по API больше не будете изменять, иначе мое приложение перестает работать

**Comment by nat236919** [comment]
@array05 My apology. That should be the last structure I significantly changed.

**Comment by array05** [comment]
> @ array05 Мои извинения. Это должна быть последняя структура, которую я значительно изменил

> @array05 My apology. That should be the last structure I significantly changed.

thanks, good work 👍
