### ISSUE TITLE
Is there a way to get time series data for the entire world?

### ISSUE THREAD

**Issue by RamanujamVaradhan** [nat236919/Covid2019API#30]
The time series API seems to return data for individual countries and provinces. Does it contain timeseries data for the world as a whole?
I do apologize if its already there. I couldnt locate it in the results.

**Comment by RamanujamVaradhan** [comment]
Also is there a way to get the time series data for the entire country of USA or any other country where the data is available province/state wise information?

**Comment by RamanujamVaradhan** [comment]
I noticed that this is available in some cases where the Country/Region is equal to  Province/State
For example: "Province/State":"France","Country/Region":"France"

But this is not consistent . For instance , in case of UK the underscore is missing in the Province/State name."Province/State":"United Kingdom","Country/Region":"United_Kingdom"

Is there anyway we can have it in a consistent way across all countries?

**Comment by RamanujamVaradhan** [comment]
Thanks for marking this as an enhancement.
Any idea when this enhancement could be made available?

**Comment by RamanujamVaradhan** [comment]
Any idea when this enhancement could be completed?
I am looking for time series data for the world as a whole. And also country wide time series data for countries for which time series data is available at the province level like China,US,Canada and Australia.

**Comment by nat236919** [comment]
https://covid2019-api.herokuapp.com/v2/timeseries/global

I've just added a new endpoint for global time series.

**Comment by RamanujamVaradhan** [comment]
Thanks.
I have started using another API for this one since there was no indication on when this enhancement would be delivered.
