### ISSUE TITLE
After update Gambia change location name

### ISSUE THREAD

**Issue by DavidBarbaran** [nat236919/Covid2019API#34]
Request https://covid2019-api.herokuapp.com/v2/current

before the update it returned **The Gambia**, now it returns "Gambia, The"

this is correct?

I inform about this problem because I match the data of this api with a json of latitudes and longitudes by the field **location**.

Thank @nat236919 (:

**Comment by nat236919** [comment]
Hi, the country names are gathered from Johns Hopkins CSSE. Unfortunately, they can be changed by them at any time.

**Comment by nat236919** [comment]
@DavidBarbaran Thank you so much. Your project looks amazing :)
