### ISSUE TITLE
Data not updated

### ISSUE THREAD

**Issue by SMFaulkner** [nat236919/Covid2019API#35]
It seems the data has not been correct for a few days now, in the UK deaths have been greater than 100 for two days and I believe higher than the 72 shown for longer.

This endpoint https://covid2019-api.herokuapp.com/v2/current shows UK deaths as 72 yet our government and the Johns Hopkins app states our deaths is 138, and 105 yesterday as can be seen here https://coronavirus.jhu.edu/map.html

@faulkner368

**Comment by nat236919** [comment]
Hello, the dashboard will always be ahead of the provided source data (https://github.com/CSSEGISandData/COVID-19) since it is only updated daily.
