### ISSUE TITLE
No data for 03/23/2020 (yesterday) 

### ISSUE THREAD

**Issue by adrianapostu** [nat236919/Covid2019API#37]
Even in [here](https://covid2019-api.herokuapp.com/docs#/v2/get_current_v2_current_get) there's no update for yesterday's data (52 new cases for yesterday worldwide). 
Anything that you can do about this or is it the original data source that's faulty here?

Cheers!

**Comment by RamanujamVaradhan** [comment]
Timeseries API is repeating  the same number for the last 2 days since yesterday,for all countries.

**Comment by nat236919** [comment]
According to https://github.com/CSSEGISandData/COVID-19/issues/1250, there seems to be a significant data change. I must modify the way to get the data from the source.
