### ISSUE TITLE
Last data update to 3/23/20

### ISSUE THREAD

**Issue by DavidBarbaran** [nat236919/Covid2019API#40]
The request https://covid2019-api.herokuapp.com/v2/current 
and https://covid2019-api.herokuapp.com/current
return data of 3/23/20 and today is 25 :(

**Comment by nat236919** [comment]
With this commit https://github.com/nat236919/Covid2019API/commit/6c3e11df810a106d0c34346a2e07d5fbb0199cc0, all APIv2 endpoints should be up-to-date now :)

**Comment by DavidBarbaran** [comment]
All good now, thank you :)
