### ISSUE TITLE
Data does not match

### ISSUE THREAD

**Issue by vitich** [nat236919/Covid2019API#7]
Data does not match
"confirmed": 64422,
"deaths": 1491,
"recovered": 7064,
[Dashbord](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6):
64458
1384
7166

**Comment by nat236919** [comment]
@vitich I do believe that Johns Hopkins CSSE's dashboard has the newest data. However, it will take sometime before that data parsing down to their repository.

Therefore, our data will stay behind their dashboard.
